# Test 1: Query the hierarchical strucutre of the administrative regions under the Flemish government.

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xkos: <http://rdf-vocabulary.ddialliance.org/xkos#> 

SELECT DISTINCT ?prov ?dist ?muni
WHERE{
  ?provId xkos:isPartOf <http://id.fedstats.be/nis/02000#id>;
  skos:prefLabel ?_prov.
  FILTER langMatches(lang(?_prov), "nl")
  BIND (str(?_prov) as ?prov)
        ?distId xkos:isPartOf ?provId;
  skos:prefLabel ?_dist.  
  FILTER langMatches(lang(?_dist), "nl")  
  BIND (str(?_dist) as ?dist) 
        ?muniId xkos:isPartOf ?distId;
  skos:prefLabel ?_muni.  
  FILTER langMatches(lang(?_muni), "nl")  
  BIND (str(?_muni) as ?muni) 
}
ORDER BY ?prov ?dist ?muni
