#list of all domain names occurring in URIs in subjects or objects

SELECT DISTINCT ?domainName 
WHERE  {
{
  ?uri ?p ?o .
} UNION {
  ?sub ?p ?uri .
  FILTER(isIRI(?uri))
}
BIND (str(?uri) as ?s)
FILTER (STRSTARTS(?s, "http://"))
BIND (IRI(CONCAT("http://", STRBEFORE(SUBSTR(?s, 8), "/"))) AS ?domainName)
}
